
export const MODIFICAR_INPUTS = 'MODIFICAR_INPUTS'
export const INICIALIZAR_CUBO = 'INICIALIZAR_CUBO'
export const INICIALIZAR_OPERACIONES = 'INICIALIZAR_OPERACIONES'
export const ESCRIBIR_ENTRADA = 'ESCRIBIR_ENTRADA'
export const ABRIR_CASO = 'ABRIR_CASO'
export const EJECUTAR_UPDATE = 'EJECUTAR_UPDATE'
export const EJECUTAR_QUERY = 'EJECUTAR_QUERY'



