//Layout
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE'
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE'

//Cubo......
export const MODIFICAR_INPUTS = 'MODIFICAR_INPUTS'
export const INICIALIZAR_CUBO = 'INICIALIZAR_CUBO'
export const INICIALIZAR_OPERACIONES = 'INICIALIZAR_OPERACIONES'
export const ESCRIBIR_ENTRADA = 'ESCRIBIR_ENTRADA'
export const ABRIR_CASO = 'ABRIR_CASO'
export const EJECUTAR_OPERACION = 'EJECUTAR_OPERACION'



